version: '3.9'
services: 
  movies-mvc:
    image: yahyamuxu/movies-mvc:latest
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - movies-db
    networks:
      - movies-network
  
  movies-db:
    image: yahyamuxu/movies-db:latest
    ports:
      - "5432:5432"
    restart: always
    networks:
      - movies-network

networks:
  movies-network: